### ISSUE TITLE
Listener for Consumers

### ISSUE THREAD

**Issue by psr323** [apache/pulsar-client-node#100]
Hi,
Is there a way to add listener callback to a consumer?

**Comment by jiazhai** [comment]
Hi @psr323 Seems there is already have the listener supported in consumer:
https://github.com/apache/pulsar-client-node/blob/master/src/Consumer.cc#L64

**Comment by psr323** [comment]
Hi @jiazhai Thanks for the response. I couldn't find any samples of this in the docs. Can you please provide an example code for this functionality

**Comment by equanz** [comment]
I'll add simple example code to repository.
https://github.com/apache/pulsar-client-node/pull/102

Other examples, please see below.
https://github.com/apache/pulsar-client-node/pull/83

**Comment by psr323** [comment]
Thanks for the example @equanz. So the current version is 1.2.0? But in the homepage the latest version is 1.1.0

**Comment by equanz** [comment]
Current version is 1.1.0(https://github.com/apache/pulsar-client-node/tags). Issue will be fixed in 1.2.0(unreleased).

**Comment by psr323** [comment]
@equanz Any tentative dates for the version 1.2.0?

**Comment by nkurihar** [comment]
@psr323 We are planning to release 1.2.0 in July.

**Comment by hrsakai** [comment]
1.2.0 was already released and usage of listener was resolved, so I close.
