### ISSUE TITLE
Implement `consumer.unsubscribe()`

### ISSUE THREAD

**Issue by alphara** [apache/pulsar-client-node#105]
The `consumer.close()` method closes consumer connection to Pulsar but does not unsubscribe from the topic. 

The `unsubscribe()` method has been implemented in the Python pulsar-client [here](https://pulsar.apache.org/api/python/2.6.0-SNAPSHOT/#pulsar.Consumer.unsubscribe).

We want request implementing a `consumber.unsubscribe()` feature in the Node.js client.

**Comment by iravishah** [comment]
Hi @sijie 

When this support will be available as a part of NPM?

**Comment by alphara** [comment]
Have you implemented the unsubscribe method in node.js client?

**Comment by equanz** [comment]
Yes. The unsubscribe method was added from [v1.3.0](https://github.com/apache/pulsar-client-node/releases/tag/v1.3.0).

**Comment by shaunek** [comment]
Can this issue be closed?

**Comment by nkurihar** [comment]
Close this issue since unsubscribe method was implemented from v1.3.0.
