### ISSUE TITLE
Support CompressionZSTD

### ISSUE THREAD

**Issue by k2la** [apache/pulsar-client-node#11]
Support ZSTD for compression.

Currently, about compression, `None`, `Zlib` and `LZ4`. are supported.
https://github.com/apache/pulsar-client-node/blob/master/src/ProducerConfig.cc#L49-L50

It is not in `client-cpp/include/pulsar/c/producer_configuration.h`. https://github.com/apache/pulsar/blob/79b88cf66eb2a4d337e21ade7f699c7d641b5c9a/pulsar-client-cpp/include/pulsar/c/producer_configuration.h#L40-L44

**Comment by hrsakai** [comment]
Closed by https://github.com/apache/pulsar-client-node/pull/121
