### ISSUE TITLE
Metadata properties incompatible with pulsar-dotnet

### ISSUE THREAD

**Issue by dionjansen** [apache/pulsar-client-node#129]
When producing messages with message properties from the node client producer and consuming them with the [pulsar-dotpulsar](https://github.com/apache/pulsar-dotpulsar) consumer it seems that the properties are mixed lost inside the message body.

#### Reproduce:

1. Modify the [producer.js](https://github.com/apache/pulsar-client-node/blob/master/examples/producer.js) to include message properties, say: `{foo: "bar"}`
1. Modify the [Consuming](https://github.com/apache/pulsar-dotpulsar/blob/master/samples/Consuming/Program.cs) sample in dotpulsar to read and log the properties, e.g.: ` Console.WriteLine("Received: " + data + ", Props Count: " + message.Properties.Count);`
1. Run both

You'd expect the consumer to log to read:

```bash
Received my-message-0, Props Count: 1
Received my-message-1, Props Count: 1
# ... etc
```

But what we actually see:

```bash
Received 

foobar
       my-message-0, Props Count: 0
Received 

foobar
       my-message-1, Props Count: 0
# ... etc
```

According to the maintainer of [pulsar-dotpulsar](https://github.com/apache/pulsar-dotpulsar) there seems to be a difference in how the raw payload is created by the node-lib, in that the metadata properties of the message are being send as part of the payload. It is unclear if this is a bug or perhaps a missing feature that [pulsar-dotpulsar](https://github.com/apache/pulsar-dotpulsar) is not making use of (yet).

#### Additional info

I did the following checks between different clients to check if this issue can be seen in different combinations:

- node-client > dotnet-client: does not work 👎 
- node-client > python-client: works 👍 
- node-client > java-client: works 👍 
- python-client > dotnet-client: works 👍 

Also this issue is only reproducible if the messages are not batched, sending a batch of messages in the above scenario works as expected.

**Comment by sijie** [comment]
@nkurihar Can you help with this issue?

**Comment by massakam** [comment]
@dionjansen @sijie 
Apparently, no matter what language the producer is written in, pulsar-dotpulsar doesn't seem to be able to get the properties of the received message when batching is enabled.

When I sent a message using the Node.js producer with batching disabled, the pulsar-dotpulsar consumer was able to handle it successfully.

To disable batching:
```js
const producer = await client.createProducer({
  topic: 'persistent://public/default/test',
  batchingEnabled: false, // Disable batching
});
```

I suspect that pulsar-dotpulsar may not be able to properly deserialize batched messages.

**Comment by massakam** [comment]
A description of "batching" in Pulsar is here:
https://pulsar.apache.org/docs/en/2.6.1/concepts-messaging/#batching

**Comment by sijie** [comment]
@massakam that was what I suspected and suggested in the slack channel.

**Comment by massakam** [comment]
Oh, I haven't joined `#dev-dotpulsar` yet.

**Comment by dionjansen** [comment]
@massakam that's definitely it. Turning batching off for both python and node clients works for the [pulsar-dotpulsar](https://github.com/apache/pulsar-dotpulsar) consumer, yet turning it on (for either producer) exposes the issue. It must be on the dotpulsar side then. I created an issue #69.

I believe this one can be closed then, thanks for the help 👍 .

**Comment by nkurihar** [comment]
https://github.com/apache/pulsar-dotpulsar/issues/61
