### ISSUE TITLE
fatal error: pulsar/c/message.h: No such file or directory

### ISSUE THREAD

**Issue by zhengdai** [apache/pulsar-client-node#139]
I'm using Ubuntu 18.04.4，and I install Pulsar C++ client by apt install ./apache-pulsar-client*.deb, and  the file libpulsar.so.2.7.0 and libpulsarnossl.so.2.7.0 are in the /usr/lib path. but when I use npm to install pulsar-client package, I still got the following error:
`
In file included from ../src/addon.cc:20:0:
../src/Message.h:24:10: fatal error: pulsar/c/message.h: No such file or directory
 #include <pulsar/c/message.h>
          ^~~~~~~~~~~~~~~~~~~~
`

**Comment by RobertLowe** [comment]
I ran into this, and I looked, at how homebrew installs it. Looks like I was missing:

```
make pulsarShared pulsarStatic
make install
```

https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libpulsar.rb#L35-L36

I was only doing `make` before.
