### ISSUE TITLE
Implement Asynchronous Processing Using C Async Function

### ISSUE THREAD

**Issue by k2la** [apache/pulsar-client-node#14]
Currently, asynchronous processing in this client library is implemented by using [NAPI::AsyncWorker](https://github.com/nodejs/node-addon-api/blob/master/doc/async_worker.md).
e.g.  https://github.com/apache/pulsar-client-node/blob/master/src/Producer.cc#L89-L120

We used `AsyncWorker` because segmentation fault about NAPI objects occurred in callback registered  with C async function.
FYI: https://github.com/nodejs/node-addon-api/issues/457

The throughput of asynchronous processing using NAPI::AsyncWorker is lower than that using C async function(e.g. pulsar_client_create_producer_async).

Therefore, we want to use C async function in order to make performance better.

**Comment by pradeep-mishra** [comment]
any update on this?

**Comment by nkurihar** [comment]
@pradeep-mishra 
Sorry, there is no update.
As described in https://github.com/apache/pulsar-client-node/pull/56, `ThreadSafeFunction` may solve this issue but we haven't tried yet.

**Comment by nkurihar** [comment]
Now AsyncWorker is replaced with async functions: https://github.com/apache/pulsar-client-node/pull/200
