### ISSUE TITLE
Implement native Node.js pulsar-client

### ISSUE THREAD

**Issue by alphara** [apache/pulsar-client-node#171]
We face some issues with the Pulsar Node.js client library, based on the C++ client library:

• We have a service that creates pulsar producers for 3 streams, consumers for 3 streams. It receives audio data from Socket.io/WebSockets and streams it to Pulsar for processing by the other services. We observed that when the service uses consumers, the `createProducer()` method often hangs without return. When we disable all consumers, the producers get created perfectly.
• The lib-pulsar crashes the Linux core rarely.
• Sometimes, Pulsar does not see that producers and consumers got disconnected from the topics. Hence, it is not possible to delete those topics with "active" subscriptions that actually became inactive.

At the same time, the Java pulsar-client works perfectly. We do not see any issues on Java. We assume that some issues might be caused by the binding of the C++ library to Node.js.

Do you have any plans to create a native pulsar-client written on Node.js entirely? What would it take from you?

**Comment by k2la** [comment]
@alphara 

We don't have no plans to implement native Node.js client at the moment.
There is a third party native Node.js Client called pulsar-flex.
https://github.com/ayeo-flex-org/pulsar-flex

**Comment by alphara** [comment]
@k2la, thank you for sharing this project! Have a great day!
