### ISSUE TITLE
Issue with node pre gyp - accessing wrong lib URL

### ISSUE THREAD

**Issue by ibtesamlatif2997** [apache/pulsar-client-node#218]
On installation of node module. I am getting this error
 
`node-pre-gyp WARN Tried to download(404): https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.6.2-node-v83-linux-x64.tar.gz `

**I think the url is wrong. It is pointed to docs url instead of libraries**

**Comment by equanz** [comment]
I've created the PR https://github.com/apache/pulsar-client-node/pull/228 for fixing this issue.
