### ISSUE TITLE
Convert project to typescript.

### ISSUE THREAD

**Issue by aahmed-se** [apache/pulsar-client-node#22]
Target version 3.3

**Comment by frejonb** [comment]
An alternative is to create a `@types/pulsar-client-node` definition in https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by aahmed-se** [comment]
that works to

**Comment by bwalendz** [comment]
I've added v1.0 types to DefinitelyTyped.

`npm install -D @types/pulsar-client`

**Comment by aahmed-se** [comment]
@bwalendz please add that to the readme.md

**Comment by nkurihar** [comment]
@bwalendz @aahmed-se 
Thank you for adding the definition and document!
By the way, do you have any idea about the procedure / policy to maintain them?

**Comment by rkaw92** [comment]
Hi! I'm running into some issues due to the typings in DefinitelyTyped being out of date (namely, `log` missing, and `listener`-based consumer unrecognized in TS). Wouldn't it be easier to maintain the type definitions inside this source repository, and always ship them together? It seems like this would make keeping things in sync easier.

**Comment by bwalendz** [comment]
@rkaw92 You can submit a pull request to the definitely typings repo if you find anything outdated and it'll get merged.

**Comment by shustsud** [comment]
@rkaw92 
Sent PR to DefinitelyTyped(pulsar-client).
 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50229

If the PR was merged, I think you can set message listener for consumer.

**Comment by massakam** [comment]
@bwalendz @rkaw92
I have added the type definitions to this repository: https://github.com/apache/pulsar-client-node/pull/140

**Comment by tisonkun** [comment]
Closed as types are provided.
