### ISSUE TITLE
The download-cpp-client.bat doesn't work on Windows

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar-client-node#256]
[This script](https://github.com/apache/pulsar-client-node/blob/master/pkg/windows/download-cpp-client.bat) might work in CI because Bash is installed in the `windows-latest` runner image.

I tried the script on my Windows. I tried CMD, PowerShell, none of them worked.

![image](https://user-images.githubusercontent.com/18204803/205291386-daabebe9-57ac-4dad-b26d-8485fe308348.png)

![image](https://user-images.githubusercontent.com/18204803/205291019-43b95f90-b362-45f0-a203-be104ac28ab9.png)

It looks like the `set arch=%1` doesn't work. In addition, there is no `mv` command on Windows.

P.S. The `pulsar-cpp` directory was created by myself. I downloaded and uncompressed the TAR file manually.

**Comment by nkurihar** [comment]
https://github.com/apache/pulsar-client-node/pull/257 fixes this issue.

**Comment by milobluebell** [comment]
你最后能用了吗？怎么解决的？  这个项目有点深海巨坑啊

**Comment by milobluebell** [comment]
你最后能用了吗？怎么解决的？ 这个项目有点深海巨坑啊  @BewareMyPower

**Comment by shibd** [comment]
This problem has been solved. What problem do you encounter?

**Comment by BewareMyPower** [comment]
@milobluebell This issue should be fixed by https://github.com/apache/pulsar-client-node/pull/257 and you could try latest commit in Windows CMD.
