### ISSUE TITLE
[feature request] Support batch receive and ack

### ISSUE THREAD

**Issue by shibd** [apache/pulsar-client-node#274]
## Motivation

You can refer to [PIP-38](https://github.com/apache/pulsar/wiki/PIP-38%3A-Batch-Receiving-Messages).

## Solution

We already support batch receive in the C++ client https://github.com/apache/pulsar-client-cpp/pull/21,  In the Node.js client side, we can wrap its interface for support.

**Comment by mguay22** [comment]
Hi @shibd - was trying to give this a go and notice there are no methods regarding the new batching implementation in https://github.com/apache/pulsar-client-cpp/blob/main/lib/c/c_Consumer.cc

I was thinking the implementation would follow a similar pattern of calling methods found there in https://github.com/apache/pulsar-client-node/blob/master/src/Client.cc - am I completely off the mark?

Also would this implementation still require the use of `ConsumerReceiveWorker`? Thanks

**Comment by shibd** [comment]
>  was trying to give this a go and notice there are no methods regarding the new batching implementation in https://github.com/apache/pulsar-client-cpp/blob/main/lib/c/c_Consumer.cc

Yes, we need to support the batch receive method on the `c` interface first.

**Comment by samwaterbury** [comment]
I saw that #357 was merged — I'm curious when the next release of the Nodejs Pulsar client might be? Or is there an outstanding todo for batch receive?

Thanks for all your contributions. 🙂

**Comment by mguay22** [comment]
Looks like this just landed in v1.10.0. Thank you! We're eager to try it out and see performance benefits from the batching.
