### ISSUE TITLE
Failed to create producer: ConnectError when upgrading to 1.8.0

### ISSUE THREAD

**Issue by ericallam** [apache/pulsar-client-node#281]
Hi there, I'm just attempting to upgrade to 1.8.0 (from 1.7.0) and I'm now getting a `Failed to create producer: ConnectError` error when creating a producer. If I downgrade back to 1.7.0 the same code works fine. 

```ts
const client = new Pulsar.Client({
  serviceUrl: "pulsar+ssl://<cluster>.<namespace>.snio.cloud:6651",
  authentication: new AuthenticationOauth2({ ... }),
  operationTimeoutSeconds: 5,
});

const producer = await client.createProducer({
  topic: "persistent://public/default/testing-topic",
});
```

I'm running on macOS 12.5.1 arm, Node.js v18.12.1

**Comment by shibd** [comment]
Hi, @ericallam Need to confirm, are you getting an auth `AuthenticationError`? In my environment I reproduce and I get an `AuthenticationError`

I get the error log:

```
Response failed for getting the well-known configuration https://dev-kt-aa9ne.us.auth0.com. Error Code 60: SSL certificate problem: unable to get local issuer certificate
```

You can add the following code to get the log information:
```
  Pulsar.Client.setLogHandler((level, file, line, message) => {
    console.log('[%s][%s:%d] %s', Pulsar.LogLevel.toString(level), file, line, message);
  });
```

**Comment by shibd** [comment]
When I use `pulsar+ssl:`, I get the same result as you: `Error: Failed to create producer: ConnectError`

The essential reason should be this:
```
Response failed for getting the well-known configuration https://dev-kt-aa9ne.us.auth0.com. Error Code 60: SSL certificate problem: unable to get local issuer certificate
```
 I will check it.

**Comment by ericallam** [comment]
Are there any workarounds for this issue @shibd?

**Comment by ericallam** [comment]
Thanks, will take a look at building from source 👍

**Comment by shibd** [comment]
Hi, Let's continue the discussion here.

https://github.com/apache/pulsar-client-node/pull/282#issuecomment-1378497083

I build from source code following Master's `README` and it worked.

I suspect maybe you're using a different server environment?

Can you test by following the steps below:

1. Refer to [How to build](https://github.com/apache/pulsar-client-node/tree/v1.8.0#how-to-build) of master README to build from the source
2. Copy this [demo](https://github.com/shibd/pulsar-node-oauth2-ssl-test/blob/main/producer-oauth2.js) to [example](https://github.com/apache/pulsar-client-node/tree/master/examples) on your host.
3. Change require
```git
const Pulsar = require('shibaodi-pulsar-client');
// change to
const Pulsar = require('../');
```
4. Run this demo.

**Comment by shibd** [comment]
### Summary

This is because cross-compilation results in the `CA cert bundle` not being set on the ARM64 Mac. Refer to this: https://github.com/apache/pulsar-client-cpp/issues/184#issuecomment-1420909521

We need to wait for this [PR](https://github.com/apache/pulsar-client-cpp/pull/190) to be released and then upgrade the CPP dependencies.

It can then be solved on arm64 by configuring `tlsTrustCertsFilePath`
```
  const client = new Pulsar.Client({
    serviceUrl: 'url',
    tlsTrustCertsFilePath:'/etc/ssl/cert.pem',
  });
```

**Comment by shibd** [comment]
v1.8.1 has already been released, and it can fix this issue.
