### ISSUE TITLE
Dependencies + subscription modes 

### ISSUE THREAD

**Issue by 1N50MN14** [apache/pulsar-client-node#32]
Hi,

Thank you for the node.js client!

Two questions:
1. `bindings` seems to be the only dependency core depends on, otherwise `commander`, `delay`, `hdr-histogram-js` and `lodash` are exclusively used in `perf`, would it be possible to move those to `devDependencies` to keep the client lightweight?  

2. Is it possible to specify subscription node? similar to:
https://github.com/apache/pulsar/blob/master/pulsar-client-go/examples/consumer/consumer.go#L40

Thanks

**Comment by hrsakai** [comment]
@1N50MN14 

>  keep the client lightweight?

I see. We will check and fix it.

> Is it possible to specify subscription node?

Yes, you can specify subscription node as following:
```
  const consumer = await client.subscribe({
    topic: 'persistent://public/default/my-topic',
    subscription: 'sub1',
    subscriptionType: 'Shared',
 //   subscriptionType: 'Failover',
//    subscriptionType: 'Exclusive',
    ackTimeoutMs: 10000,
  });
```

Thanks.

**Comment by 1N50MN14** [comment]
Ah cool you had that implemented already, thanks @hrsakai

**Comment by nkurihar** [comment]
@1N50MN14 
> bindings seems to be the only dependency core depends on, otherwise commander, delay, hdr-histogram-js and lodash are exclusively used in perf, would it be possible to move those to devDependencies to keep the client lightweight?

https://github.com/apache/pulsar-client-node/pull/35
Now those libraries were moved to devDependencies.
Thank you for your suggestion!
