### ISSUE TITLE
[feature request] Support partitioned topic reader.  

### ISSUE THREAD

**Issue by XXXMrG** [apache/pulsar-client-node#321]
The cpp client has already support partitioned topic reader.
https://github.com/apache/pulsar-client-cpp/pull/154

For now, use node client to create a reader on a partitioned topic, it will throw an error:
`[Error: Failed to create reader: OperationNotSupported]
`
Any plan to upgrade the dependencies of the CPP client ?

**Comment by shibd** [comment]
We need wait for CPP 3.2.0 release.
