### ISSUE TITLE
Schema typing support?

### ISSUE THREAD

**Issue by trevordowdle** [apache/pulsar-client-node#330]
I noticed the following pull request back in January to add schemas typing support to this library, but it appears that this hasn't been included with the latest releases.

https://github.com/apache/pulsar-client-node/pull/278

Why is that?  Is there a targeted release to include this functionality?

Thank you

**Comment by nkurihar** [comment]
Hi, I think there is no specific reason, just a timing issue.
The change will be included in 1.9.0 as its milestone.
Although there have been 2 releases(1.8.1, 1.8.2) since January, they are "patch" releases, so only bug fixes are cherry-picked.

**Comment by trevordowdle** [comment]
Okay, thank you for the insight.
