### ISSUE TITLE
Error in Running Pulser in frontend side

### ISSUE THREAD

**Issue by its0beno** [apache/pulsar-client-node#344]
So i have been trying to send a simple request as a demo on the frontend on react js but am getting 

![image](https://github.com/apache/pulsar-client-node/assets/95960560/29dab1c3-a3e8-4d3a-a3dd-40d70eb763fa)
``` import { PulsarClient, Producer, Consumer } from 'pulsar-client';
 const Pulasrclient = new PulsarClient.Client({
    serviceUrl:"pulsar://192.168.100.38:6650",
    operationTimeoutSeconds: 10,
    connectionTimeoutSeconds: 5
  }); 
async function connectToPulsar() {
  try {
    // Attempt to create a producer as a test for connection
    const producer = await client.createProducer({
      topic: 'persistent://public/default/test-topic'
    });
    await producer.close(); // Close the producer immediately after creation

    console.log("Connected to Pulsar!");
  } catch (error) {
    console.error("Failed to connect to Pulsar:", error.message);
  }
} ```

**Comment by shibd** [comment]
How did you install the Pulsar node.js client?

**Comment by its0beno** [comment]
i used 
`npm i pulsar-client`

**Comment by milobluebell** [comment]
Hi, how it going? @shibd @its0beno

**Comment by shibd** [comment]
@its0beno @milobluebell  I don't know what special environment is used on the frontend side. Can you provide more context? e.g., the version of Node.js, the specific reproduction steps, etc
