### ISSUE TITLE
Support for custom Authentication mechanism

### ISSUE THREAD

**Issue by m4rcelofs** [apache/pulsar-client-node#55]
In the Java SDK, it's easy as a consumer to use a custom authentication method.

Is there a way to do the same in the JS SDK? I tried browsing the source but couldn't find a straightforward way to accomplish it.

Example of what I'm trying to do: 
- [implement Authentication](https://github.com/TuyaInc/TuyaDemo/blob/master/open-mq-sdk/src/main/java/com/tuya/open/sdk/mq/MqAuthentication.java)
- [implement AuthenticationDataProvider](https://github.com/TuyaInc/TuyaDemo/blob/master/open-mq-sdk/src/main/java/com/tuya/open/sdk/mq/MqAuthenticationDataProvider.java)

**Comment by nkurihar** [comment]
Since this node.js client wraps C++ client, you need to implement custom authentication plugins for C++ client like:
https://github.com/apache/pulsar/tree/master/pulsar-client-cpp/lib/auth

**Comment by m4rcelofs** [comment]
Nice, thanks

**Comment by swanav** [comment]
Hey @m4rcelofs , from your example I can see that you were trying to implement the Pulsar Client for Tuya Cloud. Did you have any success doing that?

**Comment by m4rcelofs** [comment]
> Hey @m4rcelofs , from your example I can see that you were trying to implement the Pulsar Client for Tuya Cloud. Did you have any success doing that?

We did, you might wanna take a look at [fundacaocerti/pulsar-client-node](https://github.com/fundacaocerti/pulsar-client-node/tree/tuya_auth_plugin) and [fundacaocerti/pulsar](https://github.com/fundacaocerti/pulsar/tree/tuya_auth_plugin).

I left the project shortly after the message, but @lna-certi might have some better info on that.

**Comment by swanav** [comment]
Thanks! Seems interesting. I'll look into it.

**Comment by go2smartphone** [comment]
@swanav   do you have any  update on this, I am going to use for tuya as well..thanks

**Comment by swanav** [comment]
No, @go2smartphone. We dropped this approach altogether. Went ahead with the Java SDK.
