### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by mkaufmaner** [apache/pulsar-client-node#80]
@hrsakai Can you release 1.2.0?  Thank you.

**Comment by hrsakai** [comment]
@mkaufmaner 
We will release v1.2.0 in a few months.
Please wait until then.

**Comment by austince** [comment]
I think this can be closed, but looking for a tracker ticket for 1.3.0 -- is that listed somewhere or should I create a new ticket?

**Comment by hrsakai** [comment]
Yes, I close this now. 
A tracker ticket for 1.3.0 isn't listed and no new ticket required. We will release 1.3.0 in the coming weeks.

Thanks.
