### ISSUE TITLE
Support Logger and Options for Custom Logger

### ISSUE THREAD

**Issue by k2la** [apache/pulsar-client-node#9]
Support default logger and options for custom logger.
FYI: https://github.com/apache/pulsar/pull/1827

**Comment by bwalendz** [comment]
Does this have any ETA? Is there any other way to control log level now because it's actually hindering development by having it output INFO logs on the client side and being very chatty. Thanks.

**Comment by yosiat** [comment]
hi!

I played out with the code to see if I can implement something for it.
and I am ready for making a PR.

I was thinking about something like the go client -

```javascript
var client = new Pulsar.Client({
  log: function(level /* typescript enum */, file, line, message) {
    // do what you think 
  }
})
```

What do you think?

**Comment by yosiat** [comment]
Managed to figure the issues and this works.
Will make a PR soon.

**Comment by hrsakai** [comment]
Closed by https://github.com/apache/pulsar-client-node/pull/82
