### ISSUE TITLE
Does pulsar-client-node support JWT authentication?

### ISSUE THREAD

**Issue by alphara** [apache/pulsar-client-node#90]
We want our service that uses node.js pulsar client to authenticate using JWT. I don't see [here](http://pulsar.apache.org/docs/en/security-jwt/) that Node.js client supports authentication using tokens based on JSON Web Tokens.

![image](https://user-images.githubusercontent.com/5960045/82573488-36fbf580-9b5c-11ea-9de6-93504a0da733.png)

Is not this feature documented or implemented? If not implemented, we would like to request that feature.

**Comment by alphara** [comment]
We found this in code:
https://github.com/apache/pulsar-client-node/blob/master/src/AuthenticationToken.js

**Comment by jiazhai** [comment]
@alphara would like to close this issue.
