### ISSUE TITLE
Message ID for produced messages

### ISSUE THREAD

**Issue by psr323** [apache/pulsar-client-node#94]
Hi,
Currently we are not getting any response for a produced message. Is there a way to get the message ID for a message that was produced? If not, can we please have that feature?

**Comment by k2la** [comment]
There is not such a way at present but we will support it in the future.
It may take some time to support it as `pulsar-client-cpp` needs to be modified.

**Comment by psr323** [comment]
Hi @wolfstudy is this feature available for use now?

**Comment by massakam** [comment]
@psr323 No. `pulsar-client-cpp` has been modified, but it has not been released yet. The code in this repository will need to be modified after `pulsar-client-cpp` is released, so it will take some time before this feature is available.
