### ISSUE TITLE
Support getRedeliveryCount of Message

### ISSUE THREAD

**Issue by s-yoshika** [apache/pulsar-client-node#98]
I need to use `message.getRedeliveryCount`  to acknowledge the message retryed too many(or to cancel the message). It seems not to be defined in pulsar-node-client but which is already defined in [cpp client](https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/lib/c/c_Message.cc#L126).

Is this going to be supported by pulsar-node-client? or are there any other ideas to achieve what I want?

**Comment by dionjansen** [comment]
@s-yoshika I believe this has already been implemented by @frejonb in https://github.com/apache/pulsar-client-node/compare/master...frejonb:add-redelivery 👏 . @frejonb any objections to publishing a PR?

**Comment by dionjansen** [comment]
@frejonb to help out I resolved any merge conflicts with the latest `1.2.0-rc.0` in this branch: https://github.com/dionjansen/pulsar-client-node/tree/getRedeliveryCount

**Comment by frejonb** [comment]
@dionjansen it might be easier if you propose the PR from your branch. 👍

**Comment by s-yoshika** [comment]
@dionjansen Thank you for your response! Is this function already ready? And if so, Could you tell me when it is released?

**Comment by dionjansen** [comment]
@s-yoshika if by ready you mean published under a new version of this lib then no, the next version `1.2.0` is yet to be released. You can of course include the latest commit on master in your project, before the official release is ready: https://github.com/apache/pulsar-client-node/commit/a47dd211dcdd9f48cc242dc111097d8e5bc42fac

**Comment by s-yoshika** [comment]
@dionjansen Thanks! I'll wait for it to be released.

**Comment by hrsakai** [comment]
1.2.0` has already been released, so I closed this issue.
